version: '2'
networks:
 tci_tciserver:
    external: true

services:
  octopus-fe:
    build: .
    image: tikal/octopus-fe:latest
    expose:
      - 82
    ports:
      - 82:80
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.frontend.passHostHeader: "true"
      traefik.frontend.rule: "Host:octopus.tikal.io"
    networks:
      - tci_tciserver
    restart: always