version: '2'
services:
  octopus-be:
    build: .
    image: tikal/octopus-fe:latest
    ports:
      - 82:80
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.frontend.passHostHeader: "true"
      traefik.frontend.rule: "Host:octopus.tikal.io"
    restart: always